name: Feature Request ✨
description: Request a new feature or improvement!
title: "[FEATURE]: "
labels: ["feature"]
body:
  - type: markdown
      attributes:
        value: Please make sure this feature hasn't already been requested by looking through other open/closed issues.

  - type: textarea
      id: description
      attributes:
        label: Description
        description: Give us a brief description of the feature or enhancement you would like.
      validations:
        required: true

  - type: textarea
      id: additional-information
      attributes:
        label: Additional Information
        description: Provied some additional information on the feature request like proposed solutions, links, screenshots, etc.
